### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by qblaize** [YonLiud/MySQL-Discord-Bot#1]
How can I insert/ read values in DB? I would like to create changeable prefix, but i can't find out how...
Any ideas?

**Comment by YonLiud** [comment]
> How can I insert/ read values in DB:

To read the values of a database is fairly simple:
```MySQL
SELECT column_name FROM table_name;
```
To write a value:
```MySQL
INSERT INTO table1 (field1, field2) VALUES (value1, value2);
```
here's a cheat sheet on how to use MySQL: [https://devhints.io/mysql](https://devhints.io/mysql)

---

> I would like to create changeable prefix:

what do u mean by "changeable prefix"?
you could create a function in python to change the prefix by itself but I will not be able to do it for you...
sorry

**Comment by qblaize** [comment]
i mean, i want to store for evey server that use the bot the prefix, and to be changeable by a command.. someting like
<SERVER_ID> <PREFIX>

**Comment by qblaize** [comment]
i figured it out, thanksss
