### ISSUE TITLE
vars.py missing in git

### ISSUE THREAD

**Issue by Banthex** [YonLiud/MySQL-Discord-Bot#3]
Hello,

great project!
I can't find the vars.py.
Do I have to create it by myself?
I think you forgot to attach it to GitHub.

Greetings and thanks!

**Comment by YonLiud** [comment]
## Hello! Thank you for using my _MySQL-Discord-Bot_

Yes! The file has been removed for the `python-dotenv` file which is called `.env`.

to change the bot's settings just open the `.env` file in any text editor and change the environment variables to your needs!

Cheers, and thank you again for using my bot!
